steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --build-arg=VITE_API_KEY=$$VITE_API_KEY
      - --build-arg=VITE_APP_SECRET=$$VITE_APP_SECRET
      - --build-arg=VITE_BASE_URL=$$VITE_BASE_URL
      - --build-arg=VITE_BASE_URL_VERSION=$$VITE_BASE_URL_VERSION
      - -t
      - us-central1-docker.pkg.dev/forward-theorem-448209-a0/cloud-run-source-deploy/honor_hub/honor-hub:$COMMIT_SHA
      - .
    secretEnv:
      - 'VITE_API_KEY'
      - 'VITE_APP_SECRET'
      - 'VITE_BASE_URL'
      - 'VITE_BASE_URL_VERSION'

availableSecrets:
  secretManager:
    - versionName: projects/264854246496/secrets/VITE_API_KEY
      env: 'VITE_API_KEY'
    - versionName: projects/264854246496/secrets/VITE_APP_SECRET
      env: 'VITE_APP_SECRET'
    - versionName: projects/264854246496/secrets/VITE_BASE_URL
      env: 'VITE_BASE_URL'
    - versionName: projects/264854246496/secrets/VITE_BASE_URL_VERSION
      env: 'VITE_BASE_URL_VERSION'