[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[build]
  command = "npm run build"
  functions = "Netlify/functions"
  publish = "dist"

[dev]
  framework = "#static"
  targetPort = 5173
  functions = "Netlify/functions"

