name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: "forward-theorem-448209-a0"
  REGION: "us-central1"
  SERVICE_NAME: "honor-hub"
  REPO_NAME: "honor_hub"
  PROJECT_NUMBER: "264854246496"

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Clean up Git configuration
        run: |
          git config --local --unset-all 'http.https://github.com/.extraheader' || :
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get Secrets from Google Cloud
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
            secrets: |
              VITE_API_KEY:projects/$PROJECT_NUMBER/secrets/VITE_API_KEY/versions/latest
              VITE_APP_SECRET:projects/$PROJECT_NUMBER/secrets/VITE_APP_SECRET/versions/latest
              VITE_BASE_URL:projects/$PROJECT_NUMBER/secrets/VITE_BASE_URL/versions/latest
              VITE_BASE_URL_VERSION:projects/$PROJECT_NUMBER/secrets/VITE_BASE_URL_VERSION/versions/latest
      
      - name: Configure gcloud
        run: |
          gcloud config set project $PROJECT_ID
          gcloud auth configure-docker $REGION-docker.pkg.dev
      
      - name: Build and Push Docker Image
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: |
          IMAGE_NAME="${REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$SERVICE_NAME"
          
          # Build without environment variables - they'll be configured in Cloud Run
          docker buildx build \

            -t "$IMAGE_NAME:$GITHUB_SHA" \
            -t "$IMAGE_NAME:$GITHUB_SHA" \
            --push \
            --build-arg VITE_API_KEY="${{ steps.secrets.outputs.VITE_API_KEY }}" \
            --build-arg VITE_APP_SECRET="${{ steps.secrets.outputs.VITE_APP_SECRET }}" \
            --build-arg VITE_BASE_URL="${{ steps.secrets.outputs.VITE_BASE_URL }}" \
            --build-arg VITE_BASE_URL_VERSION="${{ steps.secrets.outputs.VITE_BASE_URL_VERSION }}" \     
            --push \
            -f ./Dockerfile .
      
      - name: Deploy to Cloud Run
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: |
          IMAGE_NAME="$REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$SERVICE_NAME"
          
          # Deploy to Cloud Run with environment variables set from secrets
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_NAME:$GITHUB_SHA \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --update-secrets "VITE_API_KEY=VITE_API_KEY:latest,VITE_APP_SECRET=VITE_APP_SECRET:latest,VITE_BASE_URL=VITE_BASE_URL:latest,VITE_BASE_URL_VERSION=VITE_BASE_URL_VERSION:latest"
