name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: "forward-theorem-448209-a0"
  REGION: "us-central1"
  SERVICE_NAME: "honor-hub"
  REPO_NAME: "honor_hub"

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Use v2 of buildx action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud
        run: |
          gcloud config set project $PROJECT_ID
          # Use REGION variable instead of hardcoding
          gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build and Push Docker Image
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: |
          # Construct IMAGE_NAME using environment variables
          IMAGE_NAME="$REGION-docker.pkg.dev/$GCP_PROJECT/cloud-run-source-deploy/$REPO_NAME/$SERVICE_NAME"
          
          # Single buildx command with --push (remove separate docker push)
          docker buildx build \
            --build-arg VITE_API_KEY=${{ secrets.VITE_API_KEY }} \
            --build-arg VITE_APP_SECRET=${{ secrets.VITE_APP_SECRET }} \
            --build-arg VITE_BASE_URL=${{ secrets.VITE_BASE_URL }} \
            --build-arg VITE_BASE_URL_VERSION=${{ secrets.VITE_BASE_URL_VERSION }} \
            -t $IMAGE_NAME:$GITHUB_SHA \
            --push \
            .

      - name: Deploy to Cloud Run
        run: |
          # Reconstruct IMAGE_NAME for consistency
          IMAGE_NAME="$REGION-docker.pkg.dev/$GCP_PROJECT/cloud-run-source-deploy/$REPO_NAME/$SERVICE_NAME"
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_NAME:$GITHUB_SHA \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated